// This file is auto-generated by Mingull's Minager CLI
// Do not edit manually
import { createLibraryRegistry } from "@mingull/registry";

export const registry = createLibraryRegistry({
	AngularIcon: { value: () => import("./icons/angular-icon").then((mod) => mod.AngularIcon), aliases: ["Angular"] },
	AppleIcon: { value: () => import("./icons/apple-icon").then((mod) => mod.AppleIcon), aliases: ["Apple"] },
	AriaIcon: { value: () => import("./icons/aria-icon").then((mod) => mod.AriaIcon), aliases: ["Aria"] },
	DiscordIcon: { value: () => import("./icons/discord-icon").then((mod) => mod.DiscordIcon), aliases: ["Discord"] },
	GitHubIcon: { value: () => import("./icons/github-icon").then((mod) => mod.GitHubIcon), aliases: ["GitHub"] },
	GoogleIcon: { value: () => import("./icons/google-icon").then((mod) => mod.GoogleIcon), aliases: ["Google"] },
	LinkedInIcon: { value: () => import("./icons/linkedin-icon").then((mod) => mod.LinkedInIcon), aliases: ["LinkedIn"] },
	MingullIcon: { value: () => import("./icons/mingull-icon").then((mod) => mod.MingullIcon), aliases: ["Mingull"] },
	MySQLIcon: { value: () => import("./icons/mysql-icon").then((mod) => mod.MySQLIcon), aliases: ["MySQL"] },
	NextJsIcon: { value: () => import("./icons/nextjs-icon").then((mod) => mod.NextJsIcon), aliases: ["NextJs"] },
	NodeJsIcon: { value: () => import("./icons/nodejs-icon").then((mod) => mod.NodeJsIcon), aliases: ["NodeJs"] },
	NPMIcon: { value: () => import("./icons/npm-icon").then((mod) => mod.NPMIcon), aliases: ["NPM"] },
	PayPalIcon: { value: () => import("./icons/paypal-icon").then((mod) => mod.PayPalIcon), aliases: ["PayPal"] },
	PnpmIcon: { value: () => import("./icons/pnpm-icon").then((mod) => mod.PnpmIcon), aliases: ["Pnpm"] },
	ReactIcon: { value: () => import("./icons/react-icon").then((mod) => mod.ReactIcon), aliases: ["React"] },
	Spinner: { value: () => import("./icons/spinner-icon").then((mod) => mod.Spinner), aliases: ["Spinner"] },
	TailwindIcon: { value: () => import("./icons/tailwind-icon").then((mod) => mod.TailwindIcon), aliases: ["Tailwind"] },
	TypeScriptIcon: { value: () => import("./icons/typescript-icon").then((mod) => mod.TypeScriptIcon), aliases: ["TypeScript"] },
	YarnIcon: { value: () => import("./icons/yarn-icon").then((mod) => mod.YarnIcon), aliases: ["Yarn"] },
});
